name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build-and-upload:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    #if: ${{ github.repository_owner == 'electron-react-boilerplate' }}

    strategy:
      matrix:
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install and build
        run: |
          pnpm install
          #pnpm run postinstall
          pnpm run package

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: release/build/*.dmg

      # - name: Publish releases
      #   env:
      #     # These values are used for auto updates signing
      #     APPLE_ID: ${{ secrets.APPLE_ID }}
      #     APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
      #     CSC_LINK: ${{ secrets.CSC_LINK }}
      #     CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      #     # This is used for uploading release assets to github
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     npm exec electron-builder -- --publish always --win --mac --linux
  release:
    name: Download the build result and release them
    needs: build-and-upload
    runs-on: ubuntu-latest

    steps:
      - name: Download the build result
        uses: actions/download-artifact@v3
        with:
          name: build-result

      - name: Release software
        uses: nicpollo/release-action@v1
        with:
          artifacts: '*.dmg'
          token: ${{ secrets.GITHUB_TOKEN }}
